set rtp+=~/plugins/powerline/powerline/bindings/vim  
set guifont=Meslo\ LG\ S\ DZ\ Regular\ for\ Powerline:h14
set laststatus=2  
set encoding=utf-8  
set t_Co=256  
set number  
set fillchars+=stl:\ ,stlnc:\  
set term=xterm-256color  
set termencoding=utf-8  
set background=light  
